### ISSUE TITLE
Not working with JasperReports 6

### ISSUE THREAD

**Issue by acelopezco** [FDVSolutions/DynamicJasper-core-fonts#1]
I'm trying to use this library with JasperReports 6, but I'm getting an exception:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fontBean133462384309185621' defined in URL [xx..../WEB-INF/lib/DynamicJasper-core-fonts-1.0.jar!/fonts/fonts1334623843090.xml]: Initialization of bean failed; nested exception is org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [net.sf.jasperreports.engine.fonts.SimpleFontFamily]; nested exception is java.beans.IntrospectionException: type mismatch between read and write methods`

So I was checking the fonts1334623843090.xml file and I can see that it is using some properties that are either deprecated or missing from: net.sf.jasperreports.engine.fonts.SimpleFontFamily

For example, the "normal" property has been marked as deprecated.

Any ideas how can I solve this?

Thanks

**Comment by juanalvarezg** [comment]
looks like some updates are needed, will let you know when this is done.

## 

_FDVSOLUTIONS | Collective Innovation_

_Juan Manuel Alvarez Gimenez_
CTO
Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN http://ar.linkedin.com/in/jmalvarez | SKYPE -
juan.manuel.alvarez.gimenez
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-06-08 20:41 GMT-03:00 Alexis Lopez notifications@github.com:

**Comment by mvrozanti** [comment]
Wow. Two years. Ok.

**Comment by juanalvarezg** [comment]
@mvrozanti You are very welcome to collaborate in this open source project! 
I see no shame in a project that helped thousands of people for more than 10 years.
I have to put food in my family table, I do this when I can man.

**Comment by mvrozanti** [comment]
I'm sorry I'm having a real bad time working with anything Jasper-related. I see now that this is an independent project. I really meant Jaspersoft in general. Nothing is maintained on their part, even though their software is gigantic. I understand the struggle. Do you have any ideas for alternatives? I'm giving up on Jasper-anything

**Comment by juanalvarezg** [comment]
This "core fonts" is just a convenient jar generated by iReport that bundles the ttf files and I did a maven project for that. This got old as jasper guys changed something which breaks compatibility.
This is "the new way" to export fonts https://community.jaspersoft.com/wiki/custom-font-font-extension, you can do the same!
I haven't installed jasper studio (I'm an old iReport guy), if you manage to do, send me the jar and I will publish it (you can extract the fonts from the existing old core-fonts-jar or from the project)
